---
- name: install supervisord
  include_role:
    name: geerlingguy.supervisor
  when: supervisor_install

- name: install additional packages
  yum: pkg={{ item }} state=installed
  loop:
    - MySQL-python
    - git
    - golang
