---
- name: install packages
  yum:
    name:
    - golang
    - MySQL-python
    state: installed

- name: install git temporarely
  yum:
    name: git
    state: installed
  register: gitinstalled

- name: install mysqld exporter
  shell: "go get {{ mysql_exporter_url }}"

- name: create exporter mysql user
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_pass }}"
    host: "localhost"
    priv: "*.*:SUPER,PROCESS,REPLICATION CLIENT,SELECT"

- name: install exporter.cnf
  template:
    src: "mysql_exporter.cnf.j2"
    dest: "{{ mysql_exporter_home }}/.mysql_exporter.cnf"
    group: root
    owner:root
    mode: 0644

- name: enable mysqld exporter in supervisorctl
  blockinfile:
    path: /etc/supervisord.conf
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK mysql_exporter"
    block: |
      [program:mysql_exporter]
      command={{ mysql_exporter_home }}/mysql_exporter --web.listen-address {{ mysql_exporter_ip }}:{{mysql_exporter_port }} --config.my-cnf {{ mysql_exporter_home }}/.mysql_exporter.cnf {{ mysql_exporter_extra_flags }}
      process_name=mysql_exporter
      autostart=true
      autorestart=true
      user=root
  notify:
  - restart mysql_exporter
  - check exporter port

- name: remove git if previously installed
  yum: pkg=git  state=removed
  when: gitinstalled.changed
